apiVersion: apps/v1
kind: Deployment
metadata:
  name: mohar-test01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mohar-test01
  template:
    metadata:
      labels:
        app: mohar-test01
    spec:
      containers:
        - name: mohar
          image: harshad1786/mohar-test:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: mohar-test01
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: mohar-test01
