apiVersion: apps/v1
kind: Deployment
metadata:
  name: mohar-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mohar
  template:
    metadata:
      labels:
        app: mohar
    spec:
      containers:
        - name: mohar
          image: mohar:latest
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
