apiVersion: apps/v1
kind: Deployment
metadata:
  name: harshad1786/mohar-test02
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harshad1786/mohar-test02
  template:
    metadata:
      labels:
        app: harshad1786/mohar-test02
    spec:
      containers:
        - name: mohar
          image: harshad1786/mohar-test02:latest
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              value: "8001"
---

