apiVersion: v1
kind: Service
metadata:
  name: mohar-service
spec:
  selector:
    app: mohar
  ports:
    - protocol: TCP
      port: 80 # Exposed port
      targetPort: 8081 # Container port
  type: NodePort
